version: "3.9"
services:

    redis:
        image: redis
        ports:
          - '6379:6379'

    celery-beat:
        build: ./.docker/web/
        container_name: celery-beat
        restart: always
        command: >
          sh -c "/usr/local/bin/celery -A atfalsite beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis

    celery-feed-worker:
        build: ./.docker/web/
        container_name: celery-feed-worker
        restart: always
        command: >
          sh -c "/usr/local/bin/celery -A atfalsite worker -l INFO  -Q feeds"
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis
