version: "3.9"

services:
    redis:
        image: 'bitnami/redis:latest'
        pull_policy: always
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        container_name: atfal-redis
        restart: always
        network_mode: "host"
        ports:
          - '6379:6379'

    celery-beat:
        image: atfal-site/atfal-web
        pull_policy: always
        build:
          dockerfile: ./.docker/web/Dockerfile
          context: .
        container_name: celery-beat
        restart: always
        network_mode: "host"
        entrypoint: /usr/local/bin/watchfiles --filter python '/usr/local/bin/celery -A atfalsite beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler'
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis

    celery-feed-worker:
        image: atfal-site/atfal-web
        pull_policy: always
        build:
          dockerfile: ./.docker/web/Dockerfile
          context: .
        container_name: celery-feed-worker
        restart: always
        network_mode: "host"
        entrypoint: /usr/local/bin/watchfiles --filter python '/usr/local/bin/celery -A atfalsite worker -l INFO -Q feeds'
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis

    celery-web-worker:
        image: atfal-site/atfal-web
        pull_policy: always
        build:
          dockerfile: ./.docker/web/Dockerfile
          context: .
        container_name: celery-web-worker
        restart: always
        network_mode: "host"
        entrypoint: /usr/local/bin/watchfiles --filter python '/usr/local/bin/celery -A atfalsite worker -l INFO -Q web'
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis

    celery-ai-worker:
        image: atfal-site/atfal-web
        pull_policy: always
        build:
          dockerfile: ./.docker/web/Dockerfile
          context: .
        container_name: celery-ai-worker
        restart: always
        network_mode: "host"
        entrypoint: /usr/local/bin/watchfiles --filter python '/usr/local/bin/celery -A atfalsite worker -l INFO -Q ai'
        volumes:
          - /srv/atfal-site/:/app/
        ports: []
        depends_on:
          - redis


# docker-compose  -f docker-compose-services.yml build --no-cache
# docker-compose  -f docker-compose-services.yml up -d
# docker-compose  -f docker-compose-services.yml logs -f
