# Generated by Django 4.2.1 on 2023-05-09 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_code', models.CharField(db_comment='Case Code', help_text='Enter case code', max_length=40)),
                ('facebook_post', models.URLField(db_comment='Facebook post URL', help_text='Enter Facebook case URL')),
                ('facebook_post_text', models.TextField(db_comment='Facebook post text', help_text='Facebook post text')),
                ('case_status', models.IntegerField(choices=[(0, 'Unknown, please adjust'), (1, 'Missing'), (2, 'John Doe'), (3, 'Reunited')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook_file_name', models.CharField(help_text='Facebook filename', max_length=200)),
                ('original_image', models.ImageField(upload_to='', verbose_name='Original Picture')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunite.case')),
            ],
        ),
    ]
