# Generated by Django 4.2.1 on 2023-06-05 05:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Facebook cleaned filename', max_length=200)),
                ('photo_image_url', models.CharField(help_text='Facebook media image URL', max_length=1024)),
                ('url', models.CharField(help_text='Facebook image URL', max_length=1024)),
                ('media_id', models.CharField(help_text='Facebook image URL', max_length=200)),
                ('original_image', models.ImageField(upload_to='', verbose_name='Original Picture')),
                ('ocr_text', models.CharField(db_comment='OCR Text', help_text='OCR Text', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_url', models.URLField(db_comment='Post URL', help_text='Facebook post URL')),
                ('post_id', models.CharField(db_comment='Post id', help_text='Facebook post id', max_length=200)),
                ('post_text', models.TextField(db_comment='Post text', help_text='Facebook post text', max_length=6000, null=True)),
                ('post_time', models.DateTimeField(db_comment='Post time', help_text='Facebook post time', null=True)),
                ('case_code', models.CharField(db_comment='Case Code', help_text='Case code from text', max_length=200, null=True)),
                ('facebook_id', models.CharField(db_comment='Case Code', help_text='Case code from text', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='facebook_post',
        ),
        migrations.RemoveField(
            model_name='case',
            name='facebook_post_text',
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(db_comment='Facebook post text', help_text='Facebook post text', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_code',
            field=models.CharField(db_comment='Case Code', help_text='Case code', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='facebookphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunite.facebookpost'),
        ),
        migrations.AddField(
            model_name='casepost',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunite.case'),
        ),
        migrations.AddField(
            model_name='casepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunite.facebookpost'),
        ),
        migrations.AddField(
            model_name='case',
            name='posts',
            field=models.ManyToManyField(through='reunite.CasePost', to='reunite.facebookpost'),
        ),
    ]
