# Generated by Django 4.2.1 on 2023-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0002_casepost_facebookphoto_facebookpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='facebook_id',
            field=models.CharField(db_comment='Case Code', help_text='Case code from text', max_length=200, null=True, unique=True),
        ),
    ]
