# Generated by Django 4.2.1 on 2023-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0003_alter_facebookpost_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookphoto',
            name='media_id',
            field=models.CharField(help_text='Facebook image URL', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='facebook_id',
            field=models.CharField(db_comment='Facebook post id', help_text='Facebook post id', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_id',
            field=models.CharField(db_comment='Post id', help_text='Source post id', max_length=200),
        ),
    ]
