# Generated by Django 4.2.1 on 2023-06-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0006_alter_facebookpost_facebook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='facebook_id',
            field=models.CharField(db_comment='Facebook post id', help_text='Importer Facebook post id', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_id',
            field=models.CharField(db_comment='Post id', help_text='Facebook unique post id', max_length=200, unique=True),
        ),
    ]
