# Generated by Django 4.2.1 on 2023-06-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0007_alter_facebookpost_facebook_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookphoto',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='facebookphoto',
            name='original_image',
        ),
    ]
