# Generated by Django 4.2.1 on 2023-06-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0008_remove_facebookphoto_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'ordering': ['-case_code']},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing'), (2, 'John Doe'), (3, 'Reunited'), (4, 'Deceased')], default=0),
        ),
        migrations.AlterField(
            model_name='facebookphoto',
            name='photo_image_url',
            field=models.URLField(help_text='Facebook media image URL', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facebookphoto',
            name='url',
            field=models.URLField(help_text='Facebook photo URL', max_length=1024),
        ),
    ]
