# Generated by Django 4.2.1 on 2023-06-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0009_alter_facebookpost_options_alter_case_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookphoto',
            name='media_id',
            field=models.CharField(help_text='Facebook media id (unique)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookphoto',
            name='ocr_text',
            field=models.CharField(db_comment='OCR Text', help_text='OCR Text', max_length=1024, null=True),
        ),
    ]
