# Generated by Django 4.2.2 on 2023-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0013_facebookpost_post_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='post_id',
            field=models.CharField(db_comment='Post id', help_text='Facebook unique post id', max_length=200, null=True, unique=True),
        ),
    ]
