# Generated by Django 4.2.2 on 2023-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0014_alter_facebookpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookphoto',
            name='media_id',
            field=models.CharField(help_text='Facebook media id (unique)', max_length=200, null=True, unique=True),
        ),
    ]
