# Generated by Django 4.2.5 on 2023-10-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunite', '0016_alter_facebookphoto_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookphoto',
            name='face_boxes',
            field=models.CharField(db_comment='Face Boxes', help_text='Face boxes from ai output', max_length=8192, null=True),
        ),
    ]
